version: '3.7'

volumes:
    prometheus_data: {}
    grafana_data: {}
    vm_data: {}

services:
  telegraf:
    platform: linux/amd64
    image: telegraf:1.18-alpine
    volumes:
    - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - victoriametrics
    network_mode: "host"
    restart: always

  prometheus:
    image: prom/prometheus:v2.32.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      #- /opt/grafana/prometheus-data:/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    network_mode: "host"
    restart: always

  victoriametrics:
    platform: linux/amd64
    image: victoriametrics/victoria-metrics:latest
    volumes:
      #- /opt/grafana/victoria-data:/storage
      - vm_data:/storage
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--influxListenAddr=:8089"
      - "--vmalert.proxyURL=http://vmalert:8880"
    network_mode: "host"
    restart: always

  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    network_mode: "host"
    restart: always
    deploy:
      mode: global

  grafana:
    image: grafana/grafana:latest
    user: "472"
    depends_on:
      - prometheus
      - victoriametrics
    volumes:
      #- /opt/grafana/grafana-data:/var/lib/grafana
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    network_mode: "host"
    restart: always