server:
    http_listen_port: 9080
    grpc_listen_port: 0
    log_level: "info"

positions:
    filename: /tmp/positions.yaml

clients:
    - url: http://127.0.0.1:80/loki/api/v1/push
      tenant_id: docker

scrape_configs:
  - job_name: generated-logs
    static_configs:
      - targets:
          - 127.0.0.1
        labels:
          job: generated-logs
          __path__: /var/log/generated-logs.txt
    pipeline_stages:
      - json:
          expressions:
            http_method: 'method'
            http_status: "status"
      - labels:
          http_method:
          http_status: