{
 "title": "Service Health",
 "tags": [
  "API",
  "Service"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "url_name",
    "query": {
     "query": "http_response_response_status_code_match"
    }
   }
  ]
 },
 "panels": [
  { "title": "Service Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$url_name",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "repeat": "url_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_response_result_code{server=~\"$url_name\"}",
     "legendFormat": "{{server}}"
    }
   ]
  },
  { "title": "Service/API Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Service/API Health",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "http_response_result_code",
     "legendFormat": "{{server}} : {{result}} : {{status_code}}"
    }
   ]
  },
  {
   "title": "URL Response Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "http_response_response_time", "legendFormat": "{{server}}" }
   ]
  }
 ]
}